### ISSUE TITLE
License please.

### ISSUE THREAD

**Issue by ve3** [ComputerWolf/SlickNav#10]
What license of SlickNav? MIT? GPL? or what?

Please add to you download package.
Thank you

**Comment by surgiie** [comment]
@ComputerWolf  HI im fairly new to the licensing portion of products. So i have this website im making of which id like to implement slick nav. Slick nav's min js and css files are all i need, i notice this is under the MIT license, and again im still new to this field so i just want to know how i accredit this back to you under this license.
