### ISSUE TITLE
Nice work, but not working in my CMS

### ISSUE THREAD

**Issue by kukki15344** [ComputerWolf/SlickNav#100]
I have converted my CMS into responsive-layout. Everything works very well (without Bootstrap, without other extentions....)
But in th moment I can not use "SligNav" in my CMS. It would be advantageous to use a div-container with id=menu . For many reasons I can not change unordered list "ul" a supplement id = "menu". 
And I don't use an additional trigger!  Can you expand the code for this situation:

```
<div class="nlu_horiz1 nav" id="menu" >
<ul>
	<li class="sub_no act_path active sub_first"><a href="link-1.html">Link-1</a></li>
	<li class="sub_no"><a href="link-2.html" >Link-2</a></li>
             <ul>
	....
             </ul>
	<li class="sub_no sub_last"><a href="Link-n.html">Link-n</a></li>
</ul>
</div>

```

**Comment by ComputerWolf** [comment]
@kukki15344, you can use any selector you want with SlickNav. In your example you can use `$('#menu > ul').slicknav();` and it should pick up your menu's parent ul.
