### ISSUE TITLE
Really bad lag on mobile (more on chrome mobile)

### ISSUE THREAD

**Issue by Kinsi** [ComputerWolf/SlickNav#106]
I have really a bad lag on mobile (juste on mobile) when the menu is animate.
I have jquery 1.11.2... that would be a problem?

Have you notices somth like that too?

Thx

**Comment by AshEdwardsDesign** [comment]
Hi Kinsi,

I myself don't experience any lag on a site I've used slicknav on;
http://serviceyoursmile.co.uk/

Using slicknav 1.0.3 and Jquery 1.11.3

Can you have a look at that site and let me know if you're getting any lag? If you are experiencing lag then it's most likely your device. If you're not experiencing lag then it could be something to do with your implementation of SlickNav?

Hope @ComputerWolf doesn't mind me jumping in on this ;)

**Comment by AshEdwardsDesign** [comment]
Also Kinsi, if the site you're talking about is live could you share a link so I can have a peek to see if I get lag? 

Cheers!

**Comment by Kinsi** [comment]
www.kaiserinside.com/test

It's only on mobile (chrome)

**Comment by AshEdwardsDesign** [comment]
Hi Kinsi,

I can confirm I can see lag on your site as well.

• Have you tested the site I mentioned previously to see if that works OK for you?
• Have you tried using Jquery 1.11.3?

Cheers Kinsi.

**Comment by Kinsi** [comment]
Hi Ash, yours is ok bu not perfectly smooth too...
Apparently it's a problem with Jquery animation and Slidedown/Slideup...(Slide toggle) =>
Jquery must calculate and is just a little long.

I have received the advice to use Velocity.js but i don't want to wreck the super work of @ComputerWolf ...

So no slick nav this time, i have all re-made with Css3 animations.

**Comment by ComputerWolf** [comment]
SlickNav can also use the velocity animation library if included. Just set the `animations` option to `velocity` and you should see a performance boost.
