### ISSUE TITLE
Position Fixed moving menu on other side

### ISSUE THREAD

**Issue by codesign5** [ComputerWolf/SlickNav#11]
I want to fixed the position of the menu, but when I do this, the menu move to the left position and everything inside the menu will move too. How can i fixed the position on the same "left" side. You can check my website here- http://bit.ly/1cTK3y3.

I want to give the one page scroll effect, which i have already given in high resolution screen but stuck in mobile.

**Comment by tinusmile** [comment]
Is there an off canvas menu solution for SlickNav available?
Many thanks!
