### ISSUE TITLE
How to put Slicknav on it's own level (so it doesn't push down content)

### ISSUE THREAD

**Issue by kat2014** [ComputerWolf/SlickNav#12]
Hello,

I love this responsive menu!

How would/could I get it so that Slicknav appeared on top of the rest of the HTML? Is this possible? (i.e. so that it doesn't push the rest of the content down when opened?)

I thought giving it a high z-index would do the trick, so I added the following to my CSS, but it doesn't work.

```
.js .slicknav_menu {
        z-index:99999;
    }   
```

I'd be grateful for any advice—including any that suggests my goal is a bad idea for any reason.

Thanks in advance,

Kat

**Comment by strigga** [comment]
the position fixed works with a small menu. In my case i have a long menu - so the height is larger than the screen height and i can't scroll in the menu because it is fixed. do you have a solution for this problem?
