### ISSUE TITLE
Showcase or feature

### ISSUE THREAD

**Issue by llahnoraa** [ComputerWolf/SlickNav#122]
Hello.

I love this plugin. I think this is the best one yet. I wanted to let you know that I incorporated for [sfcollege.edu](http://sfcollege.edu) and among other college's microsites such as [http://sfcollege.edu/gators](http://sfcollege.edu/gators) and [sfcollege.edu/gators](http://sfcollege.edu/zoo/)

Figured you might want to have this as a showcase on your site? Thank you.

**Comment by ComputerWolf** [comment]
@llahnoraa Thank you very much for your support. I will be happy to add you to a showcase when implemented.
