### ISSUE TITLE
improvement of keyboard accessibility

### ISSUE THREAD

**Issue by OlivierNourry** [ComputerWolf/SlickNav#127]
(tested on slicknav.com homepage with Win7 & Chrome 47)
Although it's possible to open the menu with the keyboard, focus management is not optimal. 
On large displays, on the top menu (displayed as an horizontal bar), the issue is rather obvious: the focus remains on the menu item, whereas the point of focus should be the targeted element. When pressing tab again, focus moves to the next item in the menu, which is counter-intuitive.
The same issue plays dfferently on narrow displays: there, pressing a link hides again the menu. Pressing tab again takes the focus to the next focusable element after the menu in tab order, whereas user would expect to keep on tabbing from the current position.

To fully support ARIA and accessibility, you may refer to [ARIA menubutton design pattern](https://www.w3.org/WAI/PF/aria-practices/#menubutton) for detailed instructions on keyboard management in the cases when the menu takes the form of an activable button.

**Comment by ComputerWolf** [comment]
@OlivierNourry: Thank you for your help in assessing the proper keyboard functionality. I would gladly accept a pull request with the proper functionality as it seems you have a good handle on it before I am able to get to it.

**Comment by OlivierNourry** [comment]
@ComputerWolf would love doing that, but I'm definitely more a tester than a developer. I could ruin your code by not properly modifying it, and that's something we both don't want to happen ;)
Could you use test cases or something similar? If yes, I'd be happy to help.

**Comment by ComputerWolf** [comment]
@OlivierNourry sorry I haven't gotten back around to this until now, but I have made significant changes to the keyboard navigation. I left the tab selection as-is, but I think that the arrow key navigation is much closer to what you expect. Up and down only cycles through items on the same level while right will move into a submenu and left moves back up. You have to pull the latest code to test as I have not tagged in case additional changes are necessary.

**Comment by llahnoraa** [comment]
The keyboard navigation (for mobile) for "_expanding/contracting_" nested menu aren't working, even on the latest `v1.0.10` and wondered if it had to do with `#prependTo` that won't allow to work? Here you go: [Santa Fe College](http://www.sfcollege.edu/ccs/) on the mobile version under '_Additional Navigation_' and look for `+` icon that expand the nested menu.
