### ISSUE TITLE
Menu Doubles

### ISSUE THREAD

**Issue by WaltMayhew** [ComputerWolf/SlickNav#136]
I've used slicknav before in Wordpress on a number of sites and even within this same theme, but for some reason it is creating a double menu. If I click stick menu to head, the second menu goes away but the menu that is generated obscures half the header graphic. 
The URL is http://www.noahs-ark-elc.org/test/ 
I would appreciate any suggestions on how this can be fixed. 

Thank you.

**Comment by nebrot** [comment]
Because you have two menus with your slicknav-selector ".menu":
<ul class="menu"> and <ul id="header-left-nav" class="menu">.

**Comment by WaltMayhew** [comment]
Thanks you I couldn't find the second one. If I change that to display:
none, will that fix it?

*Blessings,*

*"Trust in the Lord with all your heart and lean not on your own
understanding. In all your ways acknowledge Him and He will make your path
straight" *- Proverbs 3:5-6

**Comment by nebrot** [comment]
I don't think so. Try to use an id or change the class, so that you have only one slicknav-menu.

**Comment by WaltMayhew** [comment]
Yeah, it didn't. I'm going to have to change the code of the theme. :(

**Comment by WaltMayhew** [comment]
Found the code in the theme and changed it. Worked fine. I'll create a child theme when I get time.

Thanks for your help!
