### ISSUE TITLE
Menu items no longer respond to click events

### ISSUE THREAD

**Issue by LK6209** [ComputerWolf/SlickNav#138]
Hi, great menu, im new to code and got it to work (mostly).

My menu only has a few anchor tags its mostly just list items filled with text.

They had IDS that set a variable on click and according to that variable, a piece of content is displayed.

I have gathered from the internet that slicknav, clones your current menu and by default removes IDs because their can't be two of the same IDs.

So I've used a different strategy, replacing all IDs and using the eq() jquery function to do the same.

To my dismay, when the screen is in mobile mode, and slickNav is on screen the menu click event do not work. 

I've confirmed that remove class is set to false, element inspection of the quicknav element shows the proper class (menu_item) as well as quicknav_txtnode. I even tried targeting quicknav_txtnode with my script to no avail.

So I'm totally lost.
It appears to completely ignore the j script, still responds fine for list items with anchor tags

**Comment by ComputerWolf** [comment]
@LucianCain, you will need to use delegated click events since the SlickNav menu items are created dynamically. http://api.jquery.com/on/#direct-and-delegated-events

That or you have to attach the event handlers _after_ the SlickNav is created.
