### ISSUE TITLE
Parent menu items only

### ISSUE THREAD

**Issue by ntifosiaw** [ComputerWolf/SlickNav#153]
How can I get 1 level mobile menu at WP site with multi-level menu using Slicknav. Can't find such option in defaults, should I change plugin js?

**Comment by citytechcorp-php-ekta** [comment]
It is already done at Header.php, The code is following.




<?php wp_nav_menu(array(

	
       'theme_location' => 'primary',

	
       'menu_id' => 'primary-menu',

	
       'container_id' => 'cssmenu',

	
       'walker' => new CSS_Menu_Walker(),

	
)

	
);?>

 

You have to set menu from the backend under primary meny option, then you can make n number of submenus, it will automatically reflected on the front end and mobile responsive too.

**Comment by ntifosiaw** [comment]
Thank you, for comment, but I need parent and child items at desktop version and only parent menu items at mobile version. Same menu. Is it possible to cut child menu items from resposive using SlickNav?

**Comment by citytechcorp-php-ekta** [comment]
In mobile version, It was also done, just click  after ‘>’ this sign, then you will see those submenus, You don’t need to make different menu for Mobile and desktop. 

Examole : 
In mobile version say  About Us > {Click here}

**Comment by ntifosiaw** [comment]
ok, i see. But that's a point. I don't need submenus to shown after click in mobile version.

**Comment by ntifosiaw** [comment]
So, in mobile version all menu items should first level parent menu items, no submenu  (instead of desktop version)

**Comment by citytechcorp-php-ekta** [comment]
Have to customize it for your own, Either by js or make separate menu for mobleversion, and make primary menu disappear after certain resolution.

**Comment by ntifosiaw** [comment]
Ok, thank you, will try with jquery.slicknav.js. I think it might be useful for many users to have such option in defaults

**Comment by citytechcorp-php-ekta** [comment]
You can customize it as much as you can, My destination [HERE](https://github.com/citytechcorp-php-ekta/gulp-theme) to make wordpress theme compilation with gulp. I gave you the solution in respect of that.
