### ISSUE TITLE
Keyboard Accessibility Issue

### ISSUE THREAD

**Issue by llahnoraa** [ComputerWolf/SlickNav#158]
The keyboard navigation (for mobile) for "expanding/contracting" nested menu aren't working, even on the latest `v1.0.10` and wondered if it had to do with `#prependTo` that won't allow to work? Here you go: [Santa Fe College](http://www.sfcollege.edu/locations/northwest-campus/index) on the mobile version under `'Additional Navigation'` and look for `+` icon that expand the nested menu.

**Comment by ComputerWolf** [comment]
@llahnoraa, I am not seeing any "+" or any nested items within the markup. Not sure if the code has changed, but it looks to be functioning as expected. Please re-open if you still are having issues.

**Comment by llahnoraa** [comment]
Oh crap! I pasted the wrong URL. [It's the correct one here.](http://www.sfcollege.edu/ct3/)
