### ISSUE TITLE
Is this project DEAD?

### ISSUE THREAD

**Issue by cyberwani** [ComputerWolf/SlickNav#168]
Hi,

There is not activity since long time on this project, neither on Issues, nor Pull Requests. So, a simple question, is this project DEAD?

**Comment by userabuser** [comment]
Could very well be, the primary domain for this lib has been down for a little while too.

**Comment by ComputerWolf** [comment]
No, the project isn't dead, I have had less time to dedicate to it however. Also I had a conflict with the domain registrar and the domain is now lost. The new domain will soon be slicknav.io

**Comment by ComputerWolf** [comment]
Just as a further update, I haven't had time to make any new changes, but I have now moved the old website to github pages. I will hopefully be going through some issues and taking a look at some of the PRs.
