### ISSUE TITLE
Logo image causes SSL warning (and is not compatible with migrations)

### ISSUE THREAD

**Issue by Mugane** [ComputerWolf/SlickNav#179]
The ng_slicknav_brand image logo url needs to be RELATIVE - the full URL is used and retained across domain migrations (security and content integrity issue). The generated js code looks something like:

```
/* <![CDATA[ */
var slickNavVars = {"ng_slicknav":{"ng_slicknav_menu":"#primary-menu", 
"ng_slicknav_position":"body", "ng_slicknav_parent_links":false, 
"ng_slicknav_close_click":true,"ng_slicknav_child_links":false, "ng_slicknav_speed":200, 
"ng_slicknav_label":"MENU", "ng_slicknav_fixhead":true, "ng_slicknav_hidedesktop":"block", 
"ng_slicknav_brand":"**http:\/\/stuck.on.old.domain.this.should.be.relative!.com**\/wp-content\/uploads\/2018\/07\/logo.dark-bg.png", 
"ng_slicknav_brand_text":"", "ng_slicknav_search":true, "ng_slicknav_search_text":"search...", 
"ng_slicksearch":"**https:\/\/this.should.also.be.relative!.com**\/", "ng_slicknav_closedsymbol":"", 
"ng_slicknav_openedsymbol":"", "ng_slicknav_alt":"", "ng_slicknav_accordion":true, 
"ng_slicknav_animation_library":"jquery"}};
/* ]]> */
```

**Comment by Mugane** [comment]
So, the full url is in the setting, so left to end user to make the link relative. A bit confusing since it's auto-generated from the media library - that's the point where it should probably not incorporate the full domain.

**Comment by ComputerWolf** [comment]
The plugin simply passes through whatever element or data is placed in the "brand" property. It is up to the user to specify proper urls.

**Comment by Mugane** [comment]
Why can't it force relative urls? This is sloppy

**Comment by ComputerWolf** [comment]
I am confused about what you are expecting. The brand option will take any html and is not explicitly an image or url and can be used for any type of display. The field is simply a passthrough and does not manipulate the input.
