### ISSUE TITLE
Slicknav.io website dead

### ISSUE THREAD

**Issue by RickvanDiem** [ComputerWolf/SlickNav#190]
Slicknav website is not working anymore

**Comment by mvdobrinin** [comment]
Seems to be some kind of malware at this point.

**Comment by gordonchanhk** [comment]
domain expired

**Comment by aledc7** [comment]
it's a shame that this beautiful pluggin has been discontinued .. so sad  :(

**Comment by ComputerWolf** [comment]
I haven't had time to make any new changes, but I have now moved the old website to github pages
