### ISSUE TITLE
Making mobile menu scrollable

### ISSUE THREAD

**Issue by brianshepherd** [ComputerWolf/SlickNav#3]
Is there a way to make the mobile menu scrollable if it gets too long to fit on the screen?

**Comment by iamjon** [comment]
If someone lands here from google like I did,
You should add the scroll on the inner ul instead of the parent that way it only shows up when the menu is open. http://jsfiddle.net/dFdTq/4/

**Comment by danstoian07** [comment]
Add this css to the UL:
    overflow: auto;
    max-height: 100vh;
