### ISSUE TITLE
allowParentLinks: creates a double-link for parent links

### ISSUE THREAD

**Issue by NinaG** [ComputerWolf/SlickNav#34]
I am not sure why this happens, but my (clickable) parent links are parsed as an a-element inside an a-element. The sub-links (without further child-links) are parsed correctly with just one a-element.
.
The final code (with active JS) looks like this:

``` ...
<ul id="menu" class="slicknav_nav" style="display: block;" aria-hidden="false" role="menu">
<li class="submenu hnav-wichtig sibling first slicknav_collapsed slicknav_parent">
<a class="slicknav_item" tabindex="0" aria-haspopup="true" role="menuitem" href="#" style="outline: medium none;">
<a class="submenu sibling first" href="foo.html">Foo</a>
<span class="slicknav_arrow">►</span>
</a>
<ul class="level_2 slicknav_hidden" role="menu" style="display: none;" aria-hidden="true">
...
```

I've got this setup:

`````` <script>
  $(function(){
    $('#menu').slicknav({
      label: 'Navigation',
      duplicate: false,
      duration: 1000,
      easingOpen: "swing",
      closeOnClick: false,
      allowParentLinks: true,
      prependTo: '#mobile-anchor'
    });  
  });
</script>```
``````

**Comment by ultimike** [comment]
The "nestedParentLinks" option is a great solution, as it also helps with accessibility. Specifically, it allows parent links to be navigated to using only the tab and enter keys - something the nested "a" tags didn't allow. Thank you!

**Comment by ff-webdesigner** [comment]
love you slicknav, been using it on some wp sites for years. many of my customers -> customers complain about the fact they can'T find submenus/pages, even though we're using a quite large "+" button as slicknac arrow.

i agree: the best solution would be 1st click on parent link -> submenu open.
2nd click on parent link -> go to page.

www.windpower-gmbh.de - reduce bowser window width.
any idea how to achive this?
