### ISSUE TITLE
ID disappeared

### ISSUE THREAD

**Issue by llahnoraa** [ComputerWolf/SlickNav#4]
I added an ID to one of the "a" tag inside "li" tag, that is to trigger such as modal window, etc. 

However, in mobile, I've noticed the ID disappeared, kind of like reseting. 

That's the only issue I've encountered so far.

While I know basic javascript/jquery, have you thought about using clone() too? I might be wrong. Thanks!

**Comment by i2g-lweiss** [comment]
I have duplicate set to false and still my IDs are being stripped.  Any IDeas?

**Comment by ComputerWolf** [comment]
@i2g-lweiss there was a bug in the code which has been fixed in v1.0.7, so make sure you are using the latest version. If you are and you are still having issues, can you provide an example?

**Comment by i2g-lweiss** [comment]
Awesome thanks and wow you're quick!  Mental note to always check for a new version before posting in the future :)

**Comment by i2g-lweiss** [comment]
That worked for IDs now I'm having the problem with classes being removed, tried removeClasses: false but didn't work.  

Using Wordpress, calling SlickNav on docment ready from a script in a child theme called with wp_enqueue_scripts

**Comment by i2g-lweiss** [comment]
$('#object-nav').slicknav({
		label: "Page Menu",
		duplicate: false,
		removeClasses: false,
		prependTo: "#item-body"
	});
