### ISSUE TITLE
Unnecessary animation queue

### ISSUE THREAD

**Issue by davidsusu** [ComputerWolf/SlickNav#48]
If I click/tap twice, menu opens and closes. I suggest, then in animated state ignore user interaction or stop current animation.

If I click/tap many times, then the menu becomes crazy, and toggles until queue becomes empty.

This is a widely leaved/ignored anomaly with JQuery based menus, I know.

**Comment by ComputerWolf** [comment]
This has been fixed in version 1.0.8.
