### ISSUE TITLE
Feature Request - Callback and Opened/Closed Icon

### ISSUE THREAD

**Issue by jawinn** [ComputerWolf/SlickNav#6]
Two things I've had to add manually with the plugin. Would be great if these were added:
1. Our design calls for a close icon when the menu is open. There currently is no class to target opened/closed, or to change this icon.
2. Need some callbacks for the operation of this, such as when the menu close animation has finished.
3. Methods for opening and closing. For example, I'm using an ajax system with anchors and want to close the menu (currently doing a trigger click to force this)

**Comment by soumya85** [comment]
ComputerWolf  i have tried your method to add a close icon on slicknav menu but itsnot not working can u kindly write some kind of tutorial here that i can use as reference ....
