### ISSUE TITLE
Menu taller than screen should allow scroll

### ISSUE THREAD

**Issue by lmartins** [ComputerWolf/SlickNav#65]
When the menu is taller than the device screen it should be possible to scroll the menu. 
One way to achieve this is by applying a `max-height: 100%` to the menu container, but that can only be applied when the menu is active, otherwise the menu button won't be visible with the menu collapsed.

To achieve this we would need a class on the main container when the menu is open. 

Have you considered this?

**Comment by iamjon** [comment]
This works too https://github.com/ComputerWolf/SlickNav/issues/3
