### ISSUE TITLE
Brand name

### ISSUE THREAD

**Issue by aatosmedia** [ComputerWolf/SlickNav#67]
Is it possible to add a brand name next to menu text? It would be great if brand name could be just text or even image.

![hthda](https://cloud.githubusercontent.com/assets/6636832/6056088/a99d539a-ad14-11e4-8827-daf879447323.jpg)

**Comment by ComputerWolf** [comment]
@aatosmedia, unfortunately this feature is not currently available. It is possible to prepend some html to the menu bar using javascript after initialization, but nothing directly through SlickNav. I might add this feature in the future, but it would be nice to have some feedback on how users would like it implemented, whether it accepts simply an image or html.

**Comment by aatosmedia** [comment]
Thanks! 

There are cases that just text is enough but I think mostly company logo (image or mayby svg) is more suitable solution.

**Comment by ComputerWolf** [comment]
The `brand` option has now been added in version 1.0.2. It will accept text or any html. You may need to override the CSS since some assumptions were made.
