### ISSUE TITLE
cannot get slicknav to be visible at all

### ISSUE THREAD

**Issue by charlieapple** [ComputerWolf/SlickNav#68]
I hope someone can help. I've searched for so long for a menu exactly like this one so very happy when I found slicknav.  Unfortunately, I cannot get it to display at all.  I have been trying for 3 days and created all sorts of test pages and I cannot get to see it, even at the first stage before the media queries are set and it's meant to be visible with your own menu.  There must be a conflict with something I've got going on in my site becuase slicknav's instructions are clear and straightforward.  Please can someone take a look www.theterracewimbledon.co.uk/index2.html 
Any advice so welcome!!!!  I don't want to give up on slicknav and try another one because this one is lovely!  Thank you

**Comment by ComputerWolf** [comment]
I took a look at the link and it looks like you went with a different solution. If you want to open this back up you could provide a jsfiddle so we can take a look at what the problem might be.

**Comment by charlieapple** [comment]
Thanks Josh, I had to give up with Slicknav as I couldn’t wait anymore for a response and had to find a solution quick!  I managed to find a pure css one which is working just fine, so removed all my experimental stuff. It was a shame though because I spent ages trying Slicknav but just couldn’t get a fix for it!

Thank you for a wonderful service though….I’ll be back!

Tracy
