### ISSUE TITLE
Issue with multiple levels (2 to be specific) 

### ISSUE THREAD

**Issue by iniyazin** [ComputerWolf/SlickNav#70]
hi i am facing a very unsual problem

i have implemented slicknav in on of my projects, it has multiple menus. 

have a look http://verligte.com/sites/100k/talabul-ilm/arz-page2.htm

The menu works fine upto level1 but level 2 is not displayed properly.

as i move my mouse out of the view port area the second level also displays.

i checked on almost all devices and the issue persists. 

any help would be deeply apprecated

**Comment by ComputerWolf** [comment]
@iniyazin, I took a look into your CSS and it seems the problem is that you have a 30px height set on `.dropdown:hover>ul>li`. Because level2 is within the parent li it does not have the height to display. SlickNav does not remove classes of any menu items, so you may need to target the element based on whether it is part of SlickNav or not.

**Comment by iniyazin** [comment]
thank you so much bud. It worked!. thanks a ton :)

**Comment by iniyazin** [comment]
thank you so much buddy. it worked. thanks again

On Wed, Feb 25, 2015 at 10:42 PM, Josh <notifications@github.com> wrote:

> @iniyazin <https://github.com/iniyazin>, I took a look into your CSS and
> it seems the problem is that you have a 30px height set on
> .dropdown:hover>ul>li. Because level2 is within the parent li it does not
> have the height to display. SlickNav does not remove classes of any menu
> items, so you may need to target the element based on whether it is part of
> SlickNav or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ComputerWolf/SlickNav/issues/70#issuecomment-76005299>
> .
>



-- 
Regards
Niyaz Ahmed
+919867470726

:::: Web that never entangles or traps ::::

Mother Nature likes to read her email on computer, so should you..



PRIVILEGED - PRIVATE AND CONFIDENTIAL
This e-mail and files transmitted with it are intended solely for the use
of the addressee(s) and may contain information which is confidential or
privileged. If you are not the intended recipient, be aware that any
disclosure, copying, distribution or use of this e-mail or any attachment
is prohibited. If you receive this e-mail and you are not the addressee, or
you have received this e-mail in error, please disregard the contents of
thee-mail, delete the e-mail and notify the author immediately
