### ISSUE TITLE
mobile menu links cant scroll it down.

### ISSUE THREAD

**Issue by graydirt** [ComputerWolf/SlickNav#73]
i have 6 menu link and my problem is i cant scroll it down up to the last menu. is there any way how to fix it?.portrait and landscape?

see this test link for 768 below: 
http://www.graydirt.com/_p/slicknav/
http://codepen.io/graydirt/pen/OPrggK

**Comment by Klenkes** [comment]
Because the outermost container .slicknav_menu ist set position:fixed.
I have the same problem with a menu with 9 toplevel links. I had to reduce padding and margin so that the menu fits into a smartphone screen. At least in portrait mode.

**Comment by iamjon** [comment]
See this issue: https://github.com/ComputerWolf/SlickNav/issues/3
