### ISSUE TITLE
how do I set where on the webpage I want the menu to appear

### ISSUE THREAD

**Issue by Huaraz2** [ComputerWolf/SlickNav#78]
Hi

I am trying to set up a collapsible menu for the info on this page:
http://cardiffmathematicscodeclub.github.io/sessions.html
and I would like to do it with slicknav.  however, as you can see in the pic below the menu appears at the top above the menu we have to move between webpages. I want the slicknav menu to appear in the black box that you can see below the normal menu.  When I set the duplicate property to true, it puts the contents into the box but I can't minimise it.  How do I do this?

![slicknav screenshot problem](https://cloud.githubusercontent.com/assets/8998661/7049412/28bd0026-de11-11e4-81e9-7a776504fb59.png)

Thanks

**Comment by ComputerWolf** [comment]
@Huaraz2, there is an option `prependTo`, which defaults to the body. You can set this to a jQuery selector which will prepend the menu to that element.

**Comment by Huaraz2** [comment]
Thanks it works now
