### ISSUE TITLE
bullet points

### ISSUE THREAD

**Issue by Huaraz2** [ComputerWolf/SlickNav#79]
![slicknav bullet point screenshot](https://cloud.githubusercontent.com/assets/8998661/7049681/476c1668-de13-11e4-827a-422dd0d3e08f.png)
Hi is it possible to get each non-link item have a bullet point and if so how do I do this?

Thanks

**Comment by ComputerWolf** [comment]
@Huaraz2, all non-link items get the class `.slicknav_txtnode`, so you should be able to style it that way. You would simply need to set the list-style and the display to list item and it should show a bullet next to the item. http://jsfiddle.net/ComputerWolf/b3t4qL3o/

**Comment by Huaraz2** [comment]
Thanks for the help, it works now :smiling_imp:
