### ISSUE TITLE
Menu did not work out of that box

### ISSUE THREAD

**Issue by newseed** [ComputerWolf/SlickNav#80]
I downloaded your slicknav from slicknav.com and uploaded the entire package to a server. Out of the box the nav did not function at all.

http://www.captainjacksalaska.com/seafood/m/scripts/slicknav/demo/index.html

Can you check the condition of the zip file to see if there is something missing or corrupted?

**Comment by bvbrandon** [comment]
it works, did you try viewing on mobile? It looks bad on desktop but looks good on mobile.
