### ISSUE TITLE
Append menu to more than one element 

### ISSUE THREAD

**Issue by BassemN** [ComputerWolf/SlickNav#87]
Hello,
Firstly great plugin.
I have a question, Is there anyway to append the same menu to more than one element?
Thanks

**Comment by ComputerWolf** [comment]
@BassemN, if you simply need the same menu in multiple places you can clone the first menu and then call a second slicknav on the clone. Because of the way the methods work you can't create 2 SlickNav instances from the same menu. http://codepen.io/ComputerWolf/pen/xGdaVJ

**Comment by BassemN** [comment]
Thanks :)
