### ISSUE TITLE
Doesn't load until scroll

### ISSUE THREAD

**Issue by jasonobrown** [ComputerWolf/SlickNav#96]
The slicknav menu doesn't load until I begin scrolling.  You can view the problem here http://cornerstonecabins.com/development/index.html?redirect=false 

Just set the screen width to less that 1024.

**Comment by ComputerWolf** [comment]
@jasonobrown, this is because you have SlickNav instantiation set in a `$(window).scroll()` function. Move it out of that and you should be good to go.
