### ISSUE TITLE
init callback fires twice

### ISSUE THREAD

**Issue by liquidbook** [ComputerWolf/SlickNav#97]
I am using your init callback to append some buttons to the main container div. My issue is the init fires twice — effectively running the callback function twice. To overcome this issue I am adding a class to test  if the function has run. see code below. Maybe you could look at this fire twice issue. Thanks

http://jsfiddle.net/liquidbook/a06j6sh3/ - js only

**Comment by TraGicCode** [comment]
We are having the same issue :+1:
